### ISSUE TITLE
US-3: More in-depth results of AI models and documents

### ISSUE THREAD

**Issue by magnusgiverin** [kartAI/ntnu-kpro-ai-assistant#11]
As an application approver, I want to be able to click on results on the dashboard, including AI models, to access more in-depth result pages, so that I can perform a thorough analysis and facilitate the application approval process.

**Linked issues:**
- [x] #12
- [x] #13
- [x] #14

**Acceptance criteria:**
- [x] The user shall be able to click on each model to see more in depth responses, and have the opportunity to send information back to NorKart
- [x] The user shall be able to see the documents uploaded, and open them individually

**Comment by SverreNystad** [comment]
This is done
